/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.util.ArrayList;

public class Library {
    public boolean someLibraryMethod() {
        //TODO: add in a sout!
        return true;
    }

    public static String[] reverse(String[] arrayToReverse){
        // Instatiate Array with size
        String[] newArrayToReturn = new String[arrayToReverse.length];
        for (int i=0; i < arrayToReverse.length; i++){
            newArrayToReturn[arrayToReverse.length -1 -i] = arrayToReverse[i];
        }
        return newArrayToReturn;
    }
    // POLYMORPHISM - method overloading
    public static ArrayList<String> reverse(ArrayList<String> arrayToReverse){
        ArrayList<String> newArrayListToReturn = new ArrayList<>();
        for (int i = arrayToReverse.size() -1; i >= 0; i--){
            newArrayListToReturn.add(arrayToReverse.get(i));
        }
        return newArrayListToReturn;
    }
}
