/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bakery;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("Argument " + args[0]);
        Bakery zorksBiscuits = new Bakery();
        Bakery foodLion = new Bakery();

        Pastry newPastry = new Pastry(true, 5.99f, "Ambrosia", 8, "HUGE");
        Pastry halfPastry = new Pastry(1.60f, "Chocolate");
        System.out.println(newPastry.isGlazed());
        newPastry.eat();
        Doughnut glazedDoughnut = new Doughnut(true, 1.99f, "donut", 90, "SMALL", true);
        System.out.println(glazedDoughnut.toString());
        glazedDoughnut.eat();

    }
}
