/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package maps;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ArrayList<Boolean> hasAttended = new ArrayList<>();
        hasAttended.add(true);
        hasAttended.add(false);
        hasAttended.add(true);


        // HASHSET
        HashSet<String> classStudents = new HashSet<>();

        ArrayList<String> students = new ArrayList<>();
        students.add("Mandy");
        students.add("Josh");
        students.add("Rexie");

        // A previous inefficient Collection, u want to take of HasSet functionality
        classStudents.addAll(students);

        //HASHMAP
        //Attendance -- how do we map? String of name a bool for daily attendance
        HashMap<String, Boolean> dailyAttendance = new HashMap<>();
        dailyAttendance.put("Mandy", true);
        dailyAttendance.put("Josh", true);
        dailyAttendance.put("Rexie", true);

        dailyAttendance.put("Mandy", true);
//        dailyAttendance.replace("Mandy", true);
        System.out.println("mandy student: " + dailyAttendance.get("Mandy"));


    }
}
