/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import com.google.gson.Gson;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Gson gson = new Gson();
        String jsonReturn = gson.toJson(1);

        // Reference: https://github.com/google/gson/blob/master/UserGuide.md#TOC-Gson-With-Gradle
        int one = gson.fromJson("1", int.class);
        Integer one1 = gson.fromJson("1", Integer.class);
        Long one2 = gson.fromJson("1", Long.class);
        Boolean notTrue = gson.fromJson("false", Boolean.class);
        String str = gson.fromJson("\"abc\"", String.class);
        String[] anotherStr = gson.fromJson("[\"abc\"]", String[].class);

        ArrayList<String> colors =new ArrayList<>();
        colors.add("Red");
        colors.add("Orange");
        colors.add("Yellow");
        colors.add("Green");
        colors.add("Blue");
        colors.add("Indigo");
        colors.add("Violet");

       // OBJECTS
       Unicorn newUnicorn = new Unicorn(7,true,false, colors);
       String stringifiedUnicorn = gson.toJson(newUnicorn);
       String nightmareCorn = "{\"hornLength\":20,\"doesSparkle\":false,\"canFly\":true,\"colors\":[\"Dark\",\"Shadow\"]}";
       Unicorn javaNightmareCorn = gson.fromJson(nightmareCorn, Unicorn.class);
    }
}
