/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ZorksPetSalon;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

//        Animal newAnimal = new Animal(3,80, true, "The dominator", "Night");
        Toucan TuciTuci = new Toucan(2, 2, true, "TuciTuci", "Hawaiian shirt");

        Animal animal = new Toucan(2, 2, true, "TuciTuci", "Hawaiian shirt");
        Animal animal2 = (Animal)TuciTuci;

//        Toucan newTuci = new
    }
}
