/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void testHttpUrlConnectionReturn() throws IOException {
        // ARRANGE
        URL url = new URL("https://pokeapi.co/api/v2/pokemon/ditto");
        // Act
        HttpURLConnection sut = App.urlConnector();
        //Assert
        assertEquals("GET", sut.getRequestMethod());
        assertEquals(url, sut.getURL());
        assertNotNull(sut.getInputStream());
    }
}
