/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ZorksPetSalon;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void testToucanCreation() {
        //Arrange
        // sut = system under test == common naming convention
        Toucan sut = new Toucan(2, 2, true, "TuciTuci", "Hawaiian shirt");
        //Act
        String response = sut.fly();
        //Assert
        assertTrue(("Tuci Tuci" == response));
    }
}
